import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import { getDeliciousCookie } from '../utils'
import { ENDPOINT } from '../constants'

export default function Home() {
  const [isFetched, setIsFetched] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [cookie] = useState(getDeliciousCookie)

  const fetchToGetCookie = async () => {
    setIsLoading(true)
    try {
      await fetch(ENDPOINT, {
        mode: 'cors', 
        credentials: 'include'
      })
      setIsFetched(true)
      setIsLoading(false)
      setTimeout(() => {
        window.location = SITE_B
      }, 10)
    } catch(error) {
      console.log(error)
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Cross Domain POC - Site B</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Cross Domain Cookie - Site B</h1>
        <ul>
          <li>
            <button className={styles.button} onClick={fetchToGetCookie} disabled={isLoading}>go to siteA</button>
          </li>
          <li>
            cookie value: {cookie}
          </li>
          <li>
            hint: {isFetched ? 'fetched!' : isLoading ? 'fetching' : 'please click button' }
          </li>
        </ul>
      </main>
    </div>
  )
}
